// ... existing code ...
    let _parsed_url = url::Url::parse(&url).map_err(|e| format!("Invalid URL: {}", e))?;
    let _base_url = format!("{}://{}/", _parsed_url.scheme(), _parsed_url.host_str().unwrap_or(""));
// ... existing code ...